<?php

define( 'SWISSDELIGHT_ROOT', get_template_directory_uri() );
define( 'SWISSDELIGHT_ROOT_DIR', get_template_directory() );
define( 'SWISSDELIGHT_ASSETS_ROOT', SWISSDELIGHT_ROOT . '/assets' );
define( 'SWISSDELIGHT_ASSETS_ROOT_DIR', SWISSDELIGHT_ROOT_DIR . '/assets' );
define( 'SWISSDELIGHT_ASSETS_CSS_ROOT', SWISSDELIGHT_ASSETS_ROOT . '/css' );
define( 'SWISSDELIGHT_ASSETS_CSS_ROOT_DIR', SWISSDELIGHT_ASSETS_ROOT_DIR . '/css' );
define( 'SWISSDELIGHT_ASSETS_JS_ROOT', SWISSDELIGHT_ASSETS_ROOT . '/js' );
define( 'SWISSDELIGHT_ASSETS_JS_ROOT_DIR', SWISSDELIGHT_ASSETS_ROOT_DIR . '/js' );
define( 'SWISSDELIGHT_INC_ROOT', SWISSDELIGHT_ROOT . '/inc' );
define( 'SWISSDELIGHT_INC_ROOT_DIR', SWISSDELIGHT_ROOT_DIR . '/inc' );
