<?php

define( 'SWISSDELIGHT_MEMBERSHIP_VERSION', '1.0.1' );
define( 'SWISSDELIGHT_MEMBERSHIP_ABS_PATH', dirname( __FILE__ ) );
define( 'SWISSDELIGHT_MEMBERSHIP_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'SWISSDELIGHT_MEMBERSHIP_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'SWISSDELIGHT_MEMBERSHIP_ASSETS_PATH', SWISSDELIGHT_MEMBERSHIP_ABS_PATH . '/assets' );
define( 'SWISSDELIGHT_MEMBERSHIP_ASSETS_URL_PATH', SWISSDELIGHT_MEMBERSHIP_URL_PATH . 'assets' );
define( 'SWISSDELIGHT_MEMBERSHIP_INC_PATH', SWISSDELIGHT_MEMBERSHIP_ABS_PATH . '/inc' );
define( 'SWISSDELIGHT_MEMBERSHIP_INC_URL_PATH', SWISSDELIGHT_MEMBERSHIP_URL_PATH . 'inc' );
define( 'SWISSDELIGHT_MEMBERSHIP_LOGIN_MODAL_PATH', SWISSDELIGHT_MEMBERSHIP_INC_PATH . '/login-modal' );
define( 'SWISSDELIGHT_MEMBERSHIP_LOGIN_MODAL_URL_PATH', SWISSDELIGHT_MEMBERSHIP_INC_URL_PATH . 'login-modal' );